includes:
  - config/base_deformable_detr_vit_detection.yaml

model_config:
  deformable_detr_vit:
    backbone:
      params:
        window_block_indexes:
          - 0
          - 1
          - 3
          - 4
          - 6
          - 7
          - 9
          - 10
          
scheduler:
  type: multi_step
  params:
    use_warmup: true
    mode: iter
    lr_ratio: 0.1
    lr_steps:
      - 327778
      - 355092
    warmup_iterations: 250
    warmup_factor: 0.001

training:
  max_update: 368750
  iou_type:
    - bbox