includes:
  - config/base_simplr_vit_detection.yaml

dataset_config:
  detection:
    use_mask: true

loss:
  params:
    mask_loss_coef: 5
    dice_loss_coef: 5

model_config:
  boxer2d_vit:
    enc_dim: 960
    dec_dim: 384
    backbone:
      arch: mae_huge_patch16
      ms_params:
        scale_factors:
          - 1.0
        out_features:
          - s1
      params:
        drop_path_rate: 0.5
        window_block_indexes:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 24
          - 25
          - 26
          - 27
          - 28
          - 29
          - 30
    transformer:
      type: box_transformer_v2
      params:
        nlevel: 1
        nhead: 24
        ref_size_ratios:
          - 1
          - 2
          - 4
          - 8

optimizer:
  params:
    lr_decay_rate: 0.9
    weight_decay: 0.15
          
scheduler:
  type: multi_step
  params:
    use_warmup: true
    mode: iter
    lr_ratio: 0.1
    lr_steps:
      - 122916
      - 133159
    warmup_iterations: 250
    warmup_factor: 0.001

training:
  max_update: 138281
  batch_size: 64
  iou_type:
    - bbox
    - segm